title: Idoko Francis Ikwu
description: Experienced data enthusiast skilled in data manipulation, acquisition, cleansing, structuring, and architecting data pipelines accessible to both 
technical and non-technical teams. Possesses advanced expertise in analytical techniques like algebra and statistics. Known for exceptional organization, 
determination, and attention to detail. Proficient in both relational and non-relational databases, adept at SQL queries, proficient in product management, 
and well-versed in machine learning frameworks and algorithms. Demonstrates fluency in multiple programming languages, including MySQL, Python, R, and object-oriented 
programming (OOP).
show download: True
Theme: jeykll-theme-minimal
